### ISSUE TITLE
YAML Submission Test

### ISSUE THREAD

**Issue by SimonLucas** [SimonLucas/planet-wars-rts-submissions#1]
```yaml
id: my-awesome-agent
repo_url: https://github.com/SimonLucas/planet-wars-rts/commit/9c1133cd88217abf99a892e89d95bae6fd0ed66b
port: 9001 # might be unused
commit: 9c1133cd88217abf99a892e89d95bae6fd0ed66b  # optional
```
