### ISSUE TITLE
TeamAgentSmithV5

### ISSUE THREAD

**Issue by drumilvasani** [SimonLucas/planet-wars-rts-submissions#11]
```yaml
id: team-agent-smithV5
repo_url: https://github.com/drumilvasani/Planet-Wars-AI-Challenge-2025/commit/281cf896863f3e4c7c3103d2dbc14b7e88856c12
commit: 281cf896863f3e4c7c3103d2dbc14b7e88856c12  # optional
```
