### ISSUE TITLE
Team AgentSmith V4 Agent Testing

### ISSUE THREAD

**Issue by drumilvasani** [SimonLucas/planet-wars-rts-submissions#12]
```yaml
id: team-agent-smith-V4
repo_url: https://github.com/drumilvasani/Planet-Wars-AI-Challenge-2025/commit/24478ed01d18a3636002eb6a784888495dfdb310
commit: 24478ed01d18a3636002eb6a784888495dfdb310  # optional
```
