### ISSUE TITLE
Team AgentSmith V3 Agent Testing

### ISSUE THREAD

**Issue by drumilvasani** [SimonLucas/planet-wars-rts-submissions#13]
```yaml
id: team-agent-smith-V3
repo_url: https://github.com/drumilvasani/Planet-Wars-AI-Challenge-2025/commit/ce6fd702263343864da256dfb186c98e68a4b57e
commit: ce6fd702263343864da256dfb186c98e68a4b57e  # optional
```
