### ISSUE TITLE
Another initial test

### ISSUE THREAD

**Issue by SimonLucas** [SimonLucas/planet-wars-rts-submissions#2]
```yaml
id: another-awesome-agent
repo_url: https://github.com/SimonLucas/planet-wars-rts/commit/9c1133cd88217abf99a892e89d95bae6fd0ed66b
commit: 9c1133cd88217abf99a892e89d95bae6fd0ed66b  # optional
```
