### ISSUE TITLE
Auto polling test

### ISSUE THREAD

**Issue by SimonLucas** [SimonLucas/planet-wars-rts-submissions#4]
```yaml
id: auto-polled-test
repo_url: https://github.com/SimonLucas/planet-wars-rts/commit/9c1133cd88217abf99a892e89d95bae6fd0ed66b
commit: 9c1133cd88217abf99a892e89d95bae6fd0ed66b  # optional
```
