### ISSUE TITLE
Test with additonal sample agents

### ISSUE THREAD

**Issue by SimonLucas** [SimonLucas/planet-wars-rts-submissions#5]
```yaml
id: another-test-agent
repo_url: https://github.com/SimonLucas/planet-wars-rts/commit/343b627ec781f2fcc1138601d66877cf1f5ca5b1
commit: 9c1133cd88217abf99a892e89d95bae6fd0ed66b  # optional
```
