### ISSUE TITLE
Another YAML check

### ISSUE THREAD

**Issue by SimonLucas** [SimonLucas/planet-wars-rts-submissions#7]
```yaml
id: another-sample-agent
repo_url: https://github.com/SimonLucas/planet-wars-rts/commit/343b627ec781f2fcc1138601d66877cf1f5ca5b1
commit: 9c1133cd88217abf99a892e89d95bae6fd0ed66b  # optional
```
