### ISSUE TITLE
TeamTitansAgentV3

### ISSUE THREAD

**Issue by ammarlakho** [SimonLucas/planet-wars-rts-submissions#8]
```yaml
id: TeamTitansAgentV3
repo_url: https://github.com/abuzar-rasool/planet-wars-rts/commit/45276423a4a530dcd93330867e3b53a5bd5c2471
commit: 45276423a4a530dcd93330867e3b53a5bd5c2471  # optional
```
