### ISSUE TITLE
TeamTitansAgentV2

### ISSUE THREAD

**Issue by ammarlakho** [SimonLucas/planet-wars-rts-submissions#9]
```yaml
id: TeamTitansAgentV2
repo_url: https://github.com/abuzar-rasool/planet-wars-rts/commit/d3a995cf01120f6f1c38f34e5e78f7b0c7aa5b65
commit: d3a995cf01120f6f1c38f34e5e78f7b0c7aa5b65  # optional
```
